/*-------------------------------------------------------------------|
 |                                                                   |
 |       É·¯¥ µA¢‰A·¡Èá Nurie 1.5                                   |
 |       filename    : hgicon.h -- ´a·¡Å¥µA ”Ðe ÑA”á                |
 |       ¹A¸b·©¯¡    : 92/10/31(É¡)                                  |
 |       ¹A¸b¸a      : ·¡ »¢Àw (ID:jikchang)                         |
 |                                                                   |
 |-------------------------------------------------------------------*/

#ifndef     __HGICON_H
#define     __HGICON_H

#ifdef      __cplusplus
extern      "C" {
#endif


#define     WINCLOSE_ICON  &winclose_icon
#define     WINEND_ICON    &winend_icon
#define     WINCLOSER_ICON &winclr_icon
#define     WINENDR_ICON   &winenr_icon


#ifdef      __cplusplus
}
#endif

#endif
