/*-------------------------------------------------------------------|
 |                                                                   |
 |       É·¯¥ µA¢‰A·¡Èá Nurie 1.5                                   |
 |       filename    : key.h  -- ˆb¹· ‹¡“wÇ¡µA ”Ðe ¬w® ¸÷·        |
 |       ¹A¸b·©¯¡    : 92/10/31(É¡)                                  |
 |       ¹A¸b¸a      : ·¡ »¢Àw (ID:jikchang)                         |
 |                                                                   |
 |-------------------------------------------------------------------*/

#ifndef     __KEY_H
#define     __KEY_H


#define     RETURN      13
#define     LF          10
#define     SPACE       32
#define     HOME        327
#define     END         335
#define     PgUp        329
#define     PgDn        337
#define     DEL         339
#define     BS          8
#define     INS         338
#define     TAB         9
#define     LEFT        331
#define     RIGHT       333
#define     UP          328
#define     DOWN        336
#define     ESC         27

			/* ‹¡“wÇ¡ */
#define     F1          315
#define     F2          316
#define     F3          317
#define     F4          318
#define     F5          319
#define     F6          320
#define     F7          321
#define     F8          322
#define     F9          323
#define     F10         324

			/* Alt Ç¡µÁ· ¹¡Ðs */
#define     ALT_F1      F1 + 45
#define     ALT_F2      F2 + 45
#define     ALT_F3      F3 + 45
#define     ALT_F4      F4 + 45
#define     ALT_F5      F5 + 45
#define     ALT_F6      F6 + 45
#define     ALT_F7      F7 + 45
#define     ALT_F8      F8 + 45
#define     ALT_F9      F9 + 45
#define     ALT_F10     F10 + 45

#define     ALT_A       286
#define     ALT_B       304
#define     ALT_C       302
#define     ALT_D       288
#define     ALT_E       274
#define     ALT_F       289
#define     ALT_G       290
#define     ALT_H       291
#define     ALT_I       279
#define     ALT_J       292
#define     ALT_K       293
#define     ALT_L       294
#define     ALT_M       306
#define     ALT_N       305
#define     ALT_O       280
#define     ALT_P       281
#define     ALT_Q       272
#define     ALT_R       275
#define     ALT_S       287
#define     ALT_T       276
#define     ALT_U       278
#define     ALT_V       303
#define     ALT_W       273
#define     ALT_X       301
#define     ALT_Y       277
#define     ALT_Z       300

#define     ALT_1       376
#define     ALT_2       377
#define     ALT_3       378
#define     ALT_4       379
#define     ALT_5       380
#define     ALT_6       381
#define     ALT_7       382
#define     ALT_8       383
#define     ALT_9       384
#define     ALT_0       385

			/* Ctrl Ç¡µÁ· ¹¡Ðs */
#define     CTRL_F1     F1 + 35
#define     CTRL_F2     F2 + 35
#define     CTRL_F3     F3 + 35
#define     CTRL_F4     F4 + 35
#define     CTRL_F5     F5 + 35
#define     CTRL_F6     F6 + 35
#define     CTRL_F7     F7 + 35
#define     CTRL_F8     F8 + 35
#define     CTRL_F9     F9 + 35
#define     CTRL_F10    F10 + 35

#define     CTRL_A      1
#define     CTRL_B      2
#define     CTRL_C      3
#define     CTRL_D      4
#define     CTRL_E      5
#define     CTRL_F      6
#define     CTRL_G      7
#define     CTRL_H      8
#define     CTRL_I      9
#define     CTRL_J      10
#define     CTRL_K      11
#define     CTRL_L      12
#define     CTRL_M      13
#define     CTRL_N      14
#define     CTRL_O      15
#define     CTRL_P      16
#define     CTRL_Q      17
#define     CTRL_R      18
#define     CTRL_S      19
#define     CTRL_T      20
#define     CTRL_U      21
#define     CTRL_V      22
#define     CTRL_W      23
#define     CTRL_X      24
#define     CTRL_Y      25
#define     CTRL_Z      26

#define     CTRL_LEFT   371
#define     CTRL_RIGHT  372
#define     CTRL_HOME   375
#define     CTRL_END    373
#define     CTRL_PgUp   388
#define     CTRL_PgDn   374

			/* Shift Ç¡µÁ· ¹¡Ðs */
#define     SHIFT_F1    F1 + 25
#define     SHIFT_F2    F2 + 25
#define     SHIFT_F3    F3 + 25
#define     SHIFT_F4    F4 + 25
#define     SHIFT_F5    F5 + 25
#define     SHIFT_F6    F6 + 25
#define     SHIFT_F7    F7 + 25
#define     SHIFT_F8    F8 + 25
#define     SHIFT_F9    F9 + 25
#define     SHIFT_F10   F10 + 25

			/* Ç¡¥¡—a ¤a·¡µ¡¯a ®áÏaËa Ç¡ ¬wÈ */
#define     RIGHT_SHIFT 0x01
#define     LEFT_SHIFT  0x02
#define     CTRL        0x04
#define     ALT         0x08
#define     SCROLL_LOCK 0x10
#define     NUM_LOCK    0x20
#define     CAPS_LOCK   0x40
#define     INSERT      0x80

			/*  a¶¯a ¬wÈ */
#define     MOUSE_LEFT   400
#define     MOUSE_RIGHT  401
#define     MOUSE_MIDDLE 402

			/*  aÇa ¬wÈ */
#define     LEFTMARK     403
#define     RIGHTMARK    404

			/* Ðe/µw ¸åÑÅÇ¡ */
#define     SHIFT_SPC    500
			/* ˆa‹¡ ¡A“AÇ¡ */
#define     ALT_SPC      510

#endif
