[=1G[=15F[2J[7m ‰· ―aΗa³Λa (SCRIPT)                                                       [27m

 1] Ηa΅―a ¶΅—a I   (CRSWD1.SCF)
 2] Ηa΅―a ¶΅—a II  (CRSWD2.SCF)
 3] Θα£΅‘A·΅Θα      (TERMI.SCF)
 4] ·°΄α¤α¥...     (LOSTGOLD.SCF)
 5] Μa¶΅ Ηiσ       (PWCLUB.SCF)
 6] »΅A ΐx‹΅       (BOOM.SCF)
 7] ΡΑ΅e ¥΅Ρ΅       (STAR.SCF)
 8] «΅«΅ Ρ΅Β‰       (SBIBI.SCF)
 9] a¶α ¤a¶α ¥΅    (GAME-1.SCF)
10]  a®‰· ­A‰     (GAME-2.SCF)

