ALTER TABLE public.memos
  ADD COLUMN IF NOT EXISTS sender_user_id TEXT NOT NULL DEFAULT 'guest',
  ADD COLUMN IF NOT EXISTS recipient_user_id TEXT NOT NULL DEFAULT 'guest',
  ADD COLUMN IF NOT EXISTS title TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS content TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS is_read BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now(),
  ADD COLUMN IF NOT EXISTS read_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_memos_recipient ON public.memos(recipient_user_id);
